django/zqxt_study/minicms/minicms/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#v1.0
# urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^$', 'news.views.index', name='index'),
    # url(r'^column/(?P<column_slug>[^/]+)/$', 'news.views.column_detail', name='column'),
    # url(r'^news/(?P<article_slug>[^/]+)/$', 'news.views.article_detail', name='article'),
# ]

#v1.1
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'news.views.index', name='index'),
    url(r'^column/(?P<column_slug>[^/]+)/$', 'news.views.column_detail', name='column'),
    url(r'^news/(?P<pk>\d+)/(?P<article_slug>[^/]+)/$', 'news.views.article_detail', name='article'),
]

django/zqxt_study/minicms/news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import django.utils.timezone as timezone
from django.core.urlresolvers import reverse

import sys  
reload(sys)  
sys.setdefaultencoding('utf8')  

@python_2_unicode_compatible
class Column(models.Model):
    name = models.CharField('栏目名称', max_length=256)
    slug = models.CharField('栏目网址', max_length=256, db_index=True)
    intro = models.TextField('栏目简介', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '栏目'
        verbose_name_plural = '栏目'
        ordering = ['name'] #按照那个栏目排序
        
    def get_absolute_url(self):
        return reverse('column', args=(self.slug,))
        

@python_2_unicode_compatible
class Article(models.Model):
    column = models.ManyToManyField(Column, verbose_name='归属栏目')
    title = models.CharField("标题", max_length=256)
    slug = models.CharField('网址', max_length=256, db_index=True)

    author = models.ForeignKey('auth.User', blank=True, null=True, verbose_name='作者')
    content = models.TextField('内容', default='', blank=True)
    published = models.BooleanField('正式发布', default=True)

    #pub_date = models.DateTimeField('发表时间',  editable=True, default=timezone.now)
    #update_time = models.DateTimeField('修改时间', auto_now=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('article', args=(self.pk,self.slug))
    class Meta:
        verbose_name = '教程'
        verbose_name_plural = '教程'
        

django/zqxt_study/minicms/news/views.py
# coding: utf-8

from django.shortcuts import render
from django.http import HttpResponse
from .models import Column, Article
def index(request):
    columns = Column.objects.all()
    return render(request, 'index.html', {"columns": columns})
    
def column_detail(request, column_slug):
    column = Column.objects.get(slug=column_slug)
    return render(request, 'news/column.html', {'column': column})
    
def article_detail(request, pk, article_slug):
    article = Article.objects.get(pk=pk)
    if article_slug != article.slug:
        return redirect(article, permanent=True)
        
    return render(request, 'news/article.html', {'article': article})
    
    

django/zqxt_study/minicms/news/templates/news/article.html
{% extends "base.html" %}

{%  block title %}
{{  article.title }}
{%  endblock title %}


{%  block content %}
<h1>文章标题：{{ article.title  }}</h1>
<div id="main">
    {{  article.content }}
</div>
{%  endblock content %}

django/zqxt_study/minicms/news/templates/news/column.html
{%  extends "base.html" %}


{% block title %}
{{  column.title }}
{% endblock title %}

{%  block content %}
<p>栏目名称: {{  column.name }}</p>
<p>栏目简介：{{  column.intro }}</p>
栏目文章列表：
<ul>
    {% for article in column.article_set.all %}
        <li>
            <a href="{{  article.get_absolute_url  }}">{{  article.title  }}</a>
        </li>
    {% endfor %}
</ul>
{%  endblock content %}


django/zqxt_study/minicms/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>
            {%  block title %}
            欢迎光临小站
            {%  endblock title %}
        </title>
        {%  block css %}
        {%  endblock css %}
        
        {%  block js %}
        {%  endblock js %}
        
        
    </head>
    <body>
        {%  block content %}
            <h1>小站</h1>
        {%  endblock content %}

    </body>
</html>

django/zqxt_study/minicms/templates/index.html
{% extends "base.html" %}

{%  block title %}
首页
{%  endblock title %}

{% block content %}
<ul>
    {%  for column in columns %}
        <li>
            <a href="{{  column.get_absolute_url }}">{{  column.name  }}</a>
        </li>
    {%  endfor %}
</ul>
{% endblock content %}